sku: 0
sku_sap: 1
statut_workflow: 2
type_produit: 3
format_apprentissage: 4
pack: 5
serious_game: 6
difficulte_formation: 7
eligible_cpf: 8
certifiante: 9
formation_anglais: 10
partenaire: 11
marque: 12
duree_formation: 13
unite_duree: 14
prerequis: 15
cibles: 16
titre-web: 17
titre-print: 18
sur_titre-web: 19
sous_titre-web: 20
sous_titre-print: 21
objectifs: 22
les_plus: 23
programme-web: 24
programme-print: 25
temoignage: 26
contact_chef_marche: 27
journee_complementaire-web: 28
tarif_ht-EUR: 29
tarif_ht_journee_complementaire-EUR: 30
tarif_petite_collectivite-EUR: 31
tags: 32
intervenant: 33
image: 34
lien_video: 35
description_courte: 36
texte_seo: 37
duree_sequencee: 38
gamme: 39
family: 40
categories: 41
enabled: 42
